# Generated by Django 3.1 on 2021-01-31 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userTbl',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=15)),
                ('uId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='itemTbl',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('qty', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('date', models.DateField()),
                ('uId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.usertbl')),
            ],
        ),
    ]
